[package]
name = "stacrs"
version = "0.3.0"
edition = "2021"

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[dependencies]
geojson = "0.24.1"
pyo3 = "0.23.3"
pythonize = "0.23.0"
serde_json = "1.0.133"
stac = { version = "0.11.0", features = [
    "geoparquet-compression",
    "object-store-all",
] }
stac-api = { version = "0.6.2", features = ["client"] }
stac-duckdb = "0.0.3"
stac-types = "0.1.0"
thiserror = "2.0.4"
tokio = { version = "1.42.0", features = ["rt"] }

# We don't use duckdb directly, but we need to pin the version to v1.0 for now: https://github.com/stac-utils/stac-rs/issues/385
duckdb = { version = "=1.0.0", features = ["bundled"] }
libduckdb-sys = "=1.0.0"
openssl = { version = "0.10.68", features = ["vendored"] }
