[package]
name = "stacrs"
version = "0.3.0"
edition = "2021"

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[dependencies]
geojson = "0.24.1"
pyo3 = "0.23.3"
pythonize = "0.23.0"
serde_json = "1.0.134"
stac = { version = "0.11.1", features = [
    "geoparquet-compression",
    "object-store-all",
], git = "https://github.com/stac-utils/stac-rs" }
stac-api = { version = "0.7.0", features = [
    "client",
    "python",
], git = "https://github.com/stac-utils/stac-rs" }
stac-duckdb = { version = "0.1.0", git = "https://github.com/stac-utils/stac-rs" }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["rt"] }
