name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # https://github.com/gadomski/stacrs/issues/1
          # - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: Swatinem/rust-cache@v2
      - name: Download libduckdb
        if: ${{ matrix.os }} == "macos-latest"
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/libduckdb-osx-universal.zip
          unzip libduckdb-osx-universal.zip -d libduckdb
          echo "DYLD_LIBRARY_PATH=libduckdb:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: Sync
        run: uv sync
      - name: Lint
        run: scripts/lint
      - name: Test
        run: scripts/test
